name = "orsm-ai-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# 自定义域名配置
[[routes]]
pattern = "orsm-ai.xushibo.cn/*"
zone_name = "xushibo.cn"

[env.production]
name = "orsm-ai-worker"

# AI 绑定配置
[ai]
binding = "AI"

# 环境变量配置
[vars]
WORKERS_AI = "true"

# 开发环境配置
[env.dev]
name = "orsm-ai-worker-dev"

[env.dev.ai]
binding = "AI"

[env.dev.vars]
WORKERS_AI = "true"