name = "orsm-ai-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# 自定义域名配置
routes = [
  { pattern = "orsm-ai.xushibo.cn/*", custom_domain = true }
]

[env.production]
name = "orsm-ai-worker"

# 环境变量配置
[vars]
# 这里可以添加非敏感的环境变量
